# Generated by Django 4.1.6 on 2023-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_book', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_cart',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='id_favorites',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item_cart',
            name='id_item',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
