# Generated by Django 4.1.6 on 2023-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_purchased_books_delete_bill_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id_book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item_cart',
            name='id_book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchased_books',
            name='id_book',
            field=models.CharField(max_length=100),
        ),
    ]
