# Generated by Django 4.1.6 on 2023-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_cart', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('status', models.CharField(default='activo', max_length=100)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id_favorites', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('id_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_cart',
            fields=[
                ('id_item', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('id_cart', models.IntegerField()),
                ('id_book', models.IntegerField()),
                ('count', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('identification', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
